### ISSUE TITLE
Alert: Nuget API secure token checked in

### ISSUE THREAD

**Issue by temelj** [microsoft/VSTSAgent.PowerShell#22]
I hope this token is revoked by now, but it is very good practice not to check this in together with your code.

https://github.com/microsoft/VSTSAgent.PowerShell/blob/be02cac56160e36d71f229a99a08e13c86fde
988/appveyor.yml#L7

**Comment by jwittner** [comment]
This uses AppVeyors [Secure Variable](https://www.appveyor.com/docs/build-configuration/#secure-variables) feature.

> “Secure” variables means you can safely put them into appveyor.yml that is visible to others.
