### ISSUE TITLE
Support installation of node10-based pipelines-agent in lieu of vsts-agent

### ISSUE THREAD

**Issue by tristanbarcelon** [microsoft/VSTSAgent.PowerShell#42]
Current implementation of Find-VstsAgent filters github releases where assets are prefixed with vsts-agent. Would it be possible to support installation of pipelines-agent through an additional optional string parameter named $AgentType to Install-VstsAgent and Find-VstsAgent? It could have a ValidateSet attribute to limit values to 'vsts-agent' and 'pipelines-agent' but with a default value of 'vsts-agent` to preserve compatibility with DSC code and downstream users. Major difference between the two are outlined [here](https://github.com/microsoft/azure-pipelines-agent/blob/v3.225.0/docs/node6.md)

**Comment by jwittner** [comment]
Any reason not to expand the filter to search for both all the time? I'm assuming there's no version overlap between them or anything right?

**Comment by jwittner** [comment]
Nm, they do share versions. In that I case I like your solution for an optional 'AgentType'. Happy to review a PR with the updates too!

**Comment by tristanbarcelon** [comment]
Thanks. I'll give it a shot. :) It's been 3 yrs since I last submitted a PR to a public repo in github.

**Comment by tristanbarcelon** [comment]
@jwittner I just submitted a pull request #43.

**Comment by tristanbarcelon** [comment]
Hi @jwittner, do you need a PR to merge to master or are you performing that step? Either way, I'll be installing version 2.0.20-develop to kick the tires.

**Comment by jwittner** [comment]
> Hi @jwittner, do you need a PR to merge to master or are you performing that step? Either way, I'll be installing version 2.0.20-develop to kick the tires.

We'll let this change sit in develop for a bit in case we need anything further, then we'll pull it into master after some validation time has passed. :)
